### ISSUE TITLE
CORS error 

### ISSUE THREAD

**Issue by nigels-code** [swatisucharita/star-war-heros#1]
Hi, your code is using the swapi.co domain for it's api requests, which is returning a CORS error.  I think you need to update it to use swapi.dev. Specifically line 5 in stars-reducer.js should read: 

nextStars: 'https://swapi.dev/api/people',

Thanks for the code - I'm just implementing an infinite scroll so I'm using yours as an example.

**Comment by swatisucharita** [comment]
Thank you for the fix.
